version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  rebase-strategy: "disabled"
  versioning-strategy: increase-if-necessary
  groups:
    zhinst:
      patterns:
        - "zhinst*"
    ipywidgets:
      patterns:
        - "ipywidgets"
        - "widgetsnbextension"
        - "jupyterlab-widgets"
    sphinx:
      patterns:
        - "sphinx"
        - "sphinxcontrib*"

- package-ecosystem: github-actions
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: "daily"

- package-ecosystem: pip
  directory: /.binder
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /.github
  schedule:
    interval: daily
